[package]
name = "syt"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/anewton1998/syt"
keywords = ["YAML", "serde"]

[dependencies]
serde = {version ="1.0.217", features = ["derive"]}
serde_yml = "0.0.12"

[dev-dependencies]
tempfile = "3.15.0"
